# Considerações Finais {-}

Um dos objetivos principais desta dissertação era criar uma metodologia de campo para o estudo dos ritmos diários de atividade dos tuco-tuco de Anillaco na natureza, utilizando biologgers. Nesse sentido, consideramos que tivemos sucesso e que a metodologia de captura e recaptura apresentada no Capítulo 2 rendeu ótimos resultados, com um sucesso de recaptura e recuperação de dados maior do que 70%. Essa foi a primeira tentativa de estudo em campo de tuco-tucos no Laboratório Binacional de Cronobiologia e, além dos resultados discutidos no Capítulo 2, também possibilitou coleta de dados sobre a reprodução dessa espécie que serão publicados futuramente (Tachinardi et al., in prep.).

Os resultados discutidos no Capítulo 2 também e o uso de _biologging_ (Capítulo 1) para investigar a atividade de tuco-tucos na natureza ainda pode responder muitas novas questões. Por exemplo, os resultados do Capítulo 2 mostram que as mudanças ao longo do ano entre saída à superfície e atividade geral são distintas. Então, novos estudos em campo e em arenas seminaturais podem elucidar de maneira mais clara a origem dessas diferenças e se esses dois tipos de atividade respondem diferentemente aos desafios ambientais. Além disso, há uma redução na atividade geral dos tuco-tucos no Inverno, que volta a aumentar em outubro, no Outono. Como foi discutido no Capítulo 2, essas mudanças ao longo do ano podem estar relacionadas ao início da estação reprodutiva, assim como acontece em outras espécies. Portanto, futuros estudos de _biologging_ focados no Inverno e Outono e na diferença entre machos e fêmeas podem elucidar se essas mudanças anuais se repetem em outros anos e se elas estão relacionadas a comportamentos sexuais e reprodutivos.

O uso de _hidden_ _Markov_ _models_ (HMM) na análise dos dados de acelerometria possibilitou entender melhor as mudanças na atividade geral dos tuco-tucos. Anteriormente, os estudos com acelerômetros em tuco-tucos usaram um valor de limiar baseado na média diária da atividade para definir o que era atividade ou repouso [@jannetti2019]. Esse método, apesar da simplicidade, limita os tipos de análise ou de comportamentos que podemos extrair dos dados, já que a definição de um limiar não é tão simples para mais do que dois comportamentos. Os HMM, em contrapartida, já são bastante utilizados para a análise de dados de acelerometria em animais [@leos-barajas2017; @mcclintock2020]. No nosso caso, apesar de algumas limitações, o uso de HMMs permitiu, a partir da distribuição dos próprios dados, classificar três estados comportamentais utilizando a atividade geral (Capítulo 2). O uso futuro desse tipo de modelo nos permitirá explorar ainda mais a fundo como os comportamentos dos tuco-tucos mudam em diferentes estações ou quando submetidos a diferentes desafios ambientais. Outro dado inédito (Capítulo 2) foi o cruzamento dos dados de saída à superfície e dos estados comportamentais, que revelou diferenças comportamentais entre tuco-tucos de Anillaco em condição de vida-livre e semi-natural. Nesses resultados, vimos que os tuco-tucos passam relativamente pouco tempo em repouso quando estão na superfície quando comparados a  tuco-tucos em arenas seminaturais [@jannetti2019], os quais parecem apresentam maior tempo diário na superfície. Esses resultados apontam o uso dos HMMs como uma importante ferramenta em estudos cronobiológicos de campo, permitindo explorar as diferenças nos padrões diários de diferentes comportamentos. Além disso, a possibilidade de utilizarmos HMMs de forma supervisionada nas arenas e em laboratório pode permitir a identificação de comportamentos específicos, algo que não é possível com os dados atuais.
