#' -------------------------------------------------------------------------
#' Script to asses the best smooth window to use when calculating the
#' accelerometer's Dynamic Acceleration and VeDBA. Based on Shepard (2008).
#'
#' The value found here is the default value for the smoothing window in the DBA 
#' function.
#'
#' Based on the plot generated by this script the default smoothing window was 
#' set at 4 sec.
#' -------------------------------------------------------------------------
library(data.table)
library(tidyr)
library(zoo)
library(ggplot2)
library(dplyr)
library(egg)

tuco = readRDS("01_data/rds/tuco_10hz_smooth_subset.rds") # This is a subset of 4 animal/4 days
tuco[, day_number := NULL]
tuco[, datetime := NULL]

# Calculate VEDBA using different smoothing windows to subtract the static acceleration
windows = seq(from = 1, to = 12, by = 1)
for (i in windows) {
    tuco[, Xd := X - frollmean(x = X, n = i*10, align = "left"), by = ID]
    tuco[, Yd := Y - frollmean(x = Y, n = i*10, align = "left"), by = ID]
    tuco[, Zd := Z - frollmean(x = Z, n = i*10, align = "left"), by = ID]

    tuco[, paste0("vedba", i) := sqrt(Xd^2 + Yd^2 + Zd^2)]
    tuco[, c("Xd","Yd","Zd") := NULL]
}
tuco[, c("X","Y","Z") := NULL]

# Calculate mean VEDBA over 10 sec
setkey(tuco, ID)
tuco10 = tuco[, lapply(X = .SD, FUN = rollapply, width = 100, by = 100, mean), by = ID]

# Calculate mean VEDBA over 1h
setkey(tuco, ID)
tuco10000 = tuco[, lapply(X = .SD, FUN = rollapply, width = 10000, by = 10000, mean), by = ID]

# Transform wide dataset into long dataset
tuco10 = pivot_longer(tuco10, 2:length(tuco10), names_to = "smooth", values_to = "vedba")
tuco10000 = pivot_longer(tuco10000, 2:length(tuco10000), names_to = "smooth", values_to = "vedba")

# Reorganize factor levels
i = seq(0, 12, by = 1)
tuco10$smooth = factor(tuco10$smooth,
                       levels = c(paste0("vedba", i)))

tuco10000$smooth = factor(tuco10000$smooth,
                       levels = c(paste0("vedba", i)))

tuco_plot_10s = tuco10 %>% 
    group_by(smooth) %>% 
    summarise(mean = mean(vedba, na.rm = T), n = n(), sd = sd(vedba, na.rm = T), se = sd/sqrt(n)) 

tuco_plot_1h = tuco10000 %>% 
    group_by(smooth) %>% 
    summarise(mean = mean(vedba, na.rm = T), n = n(), sd = sd(vedba, na.rm = T), se = sd/sqrt(n))

# PLOTS -------------------------------------------------------------------
point_10s = ggplot(tuco_plot_10s) +
    geom_pointrange(aes(x = smooth, y = mean, ymin = mean - sd, ymax = mean + sd)) +
    theme_article() + 
    theme(panel.grid.major.y = element_line(color = "lightgrey", linetype = "dashed"))

point_1h = ggplot(tuco_plot_1h) +
    geom_pointrange(aes(x = smooth, y = mean, ymin = mean - sd, ymax = mean + sd)) +
    theme_article() + 
    theme(panel.grid.major.y = element_line(color = "lightgrey", linetype = "dashed"))

boxplot_10s = ggplot(tuco10) + 
        geom_boxplot(aes(x = smooth, y = vedba)) +
        theme_article() + 
        theme(panel.grid.major.y = element_line(color = "lightgrey", linetype = "dashed"))

boxplot_1h = ggplot(tuco10000) + 
    geom_boxplot(aes(x = smooth, y = vedba)) +
    theme_article() + 
    theme(panel.grid.major.y = element_line(color = "lightgrey", linetype = "dashed"))

ggsave("05_figures/smoothing_window/smoothing_pointrange_10s.png", point_10s, "png", width = 10, height = 8)
ggsave("/smoothing_window/smoothing_pointrange_1h", point_1h, "png", "05_figures", width = 10, height = 8)
ggsave("/smoothing_window/smoothing_boxplot_10s", boxplot_10s, "png", "05_figures", width = 10, height = 8)
ggsave("/smoothing_window/smoothing_boxplot_1h", boxplot_1h, "png", "05_figures", width = 10, height = 8)