# Chronobiology in the wild: toolkit to study daily rhythms in free-living animals

_Jefferson T. Silvério, Patricia Tachinardi_

\  

*Published in Sleep Science - Volume 13, Supplement 2. 2020.*

\  

Since chronobiology’s foundation has been laid out in the 60s, tremendous progress has been made regarding our knowledge about the nature of the circadian clock, its molecular bases and its synchronization by photic and non-photic stimuli. The majority of these studies have been done in laboratory settings, which, although important, lack information about the adaptive value, ecological significance and plasticity of the biological rhythms in the wild. This concern has been raised several times, along with the development of the field. Methodological difficulties have been the biggest challenges of field studies. However, the recent development of new techniques is opening a wide range of opportunities to investigate biological rhythms in free-ranging animals. In this review, we promote an ecological approach to biological clocks and highlight some methods and newer technologies that can be used to study biological clocks in the wild, along with some examples.

\  

_*Keywords:* biological rhythms; wild-clocks; field and laboratory; biologger; free-ranging; activity patterns._

## Introduction

Endogenous circadian clocks enable animals to anticipate changes in physiology and behavior to the daily changes in the environment synchronizing their internal state with the 24-hour environmental cycles. Our knowledge of the function and mechanism of these clocks has grown extensively in different levels of organizations such as molecular, cellular, tissue and organs. Most of the studies of the mechanisms and nature of the clock itself has been done in the laboratory, under controlled conditions [@enrightEcologicalAspectsEndogenous1970; @morganEcologicalSignificanceBiological2004]. Using the laboratory approach, several endogenous circadian rhythms were described in a diverse range of organisms, from mammals to birds, insects and the molecular clocks of bacteria. However, the physiology and behavior of a laboratory animal can be unrepresentative of what happens in the field [@calisiLabFieldExperiments2009; @willmerEnvironmentalPhysiologyAnimals2005]. Several authors have brought the argument that we know very little about the ecological significance of circadian rhythms [@enrightEcologicalAspectsEndogenous1970; @halleActivityPatternsSmall2000; @helmTwoSidesCoin2017]. The central argument is that to understand the adaptive significance of circadian rhythms, the diversity of temporal strategies and how flexible circadian rhythms are, we must turn to ecological studies in free-living animals. To fill this gap, several recent studies on animal chronobiology have been carried out in free-living animals. These studies investigate the interplay between the endogenous circadian pacemaker and the biotic and abiotic stimuli acting on the plasticity of overt daily rhythms. These studies have suggested that biological rhythms in the wild are much more flexible than previously thought [@hutSearchTemporalNiche2012].

The advancement of chronobiological studies in the field has long been challenged by the difficulty of measuring biological rhythms in nature. In the laboratory, locomotor activity and body temperature (Tb) rhythms have been widely used due to ease of measurement and replicability. Commonly, activity is measured by counting running wheel revolutions, by detecting movement with an infrared motion sensor placed above the animal’s cage or by implanting a wireless activity sensor in the animal [@blanchongNocturnalDiurnalRhythms1999]. Measurements of Tb, in turn, are more invasive and can require more expensive equipment. Usually, Tb sensors are implanted surgically in the peritoneal cavity of the animal. These sensors can either be loggers, in which the data is stored in the device or transmitters, which send data to receivers outside the animal [@weinertDiurnallyChangingEffects1998]. When studying free-living animals, however, many of these commonly used methods to study locomotor activity and Tb rhythms are very difficult or simply impossible to be deployed, being it because of technical or financial drawbacks. 

Recent technological advances, such as the miniaturization of sensors and logging devices, have opened a wide variety of opportunities to study biological rhythms in free-living animals. In this mini-review, we will discuss some of the methods being used to assess behavioral and physiological rhythms of free-living animals in both populational and individual levels. We will focus on methods used in the research of terrestrial mammals, although many of them can also be deployed to other taxa and to aquatic and flying animals [@dominoniMethodsFieldChronobiology2017]. It is important to note that most methods require handling the animal for implanting or externally attaching a device. Thus, researchers should always take into account any possible effects this manipulation can have on the animals and on the data obtained [@chmuraBiologgingPhysiologicalEcological2018].

## Chronobiological studies in free-living animals

### Populational Rhythms

Most of the early investigations of clocks in the wild have been carried out focusing on populational rhythms, using observational and trapping methods [@daanShorttermRhythmsForaging1978; @halleActivityPatternsSmall2000; @kenagyPeriodicityDailyActivity1976]. Using live-traps to infer activity rhythms can be done setting a grid of traps in the study site and then counting the number of captures for a chosen time interval. For example, using hourly record of vole (_Microtus arvalis_) trappings in the wild it was possible to record the pattern of daily activity in these species and their ultradian components [@gerkemaUltradianRhythmsBehavior1985]. If a higher temporal resolution is required, it is possible to combine live-trapping and direct observations to record the exact time the animals were trapped. Using this approach it was shown that Kangaroo rats (genus Dipodomys) display seasonal change in their start and end time of activity, which might be related to the length changes of sunset [@kenagyPeriodicityDailyActivity1976]. Both observational and live-trapping methods are limited in the range of habitats and diversity of animals they can be applied to. Observational studies have to be done in diurnal species living in open habitats, otherwise, it becomes unfeasible to observe the study species. Small nocturnal animals and animals living in habitats with dense vegetation are not well suited for this technique. On the other hand, trapping studies face the problems of how easily individuals of the study species can be trapped [@halleActivityPatternsSmall2000]. Both of the above mentioned examples were done in species that are relatively easy to capture in live traps. Kangaroo rats, for example, do not exhibit an aversion to the traps and manipulation. Voles, in turn, leave recognizable tracks aboveground that can guide trap placement and increase trapping success.

More recently, the use of time-stamped camera-trap images has expanded the study of population activity rhythms to species that cannot be easily observed or captured [@freyInvestigatingAnimalActivity2017; @rowcliffeQuantifyingLevelsAnimal2014]. Moreover, this non-invasive technique can be used to simultaneously monitor several species that occur in the same area. For example, Mendes and colleagues [@mendesLandscapeHumanFear2020] did an extensive camera-trap study to evaluate the changes in daily activity rhythms of 17 rainforest-dwelling mammal species in response to human disturbance. They found out that there was a shift in the timing of activity in highly disturbed areas, with some species becoming more nocturnal and others more diurnal. Species that were susceptible to preying or hunting were more likely to show activity time shifts. Possible drawbacks of using camera-traps are camera placement bias, detectability of the animals in the camera and the assumption that all individuals of the population will display peak activity at the same time [@freyInvestigatingAnimalActivity2017; @rowcliffeQuantifyingLevelsAnimal2014].

### Individual behavioral rhythms

In general, to study individual daily activity patterns it is necessary to continuously follow and record movement and behavior of the same individual for many days [@daanAdaptiveDailyStrategies1981], which can be very challenging in the field. Individual monitoring can be done using direct observations [@evertsSeasonalVariationDaily2004; @tomotaniPosefeitosSincronizacaoEm2011], but this method restricts the monitoring of the animal to the times when it is visible. For continuous measurements, it is usually required to attach a device to the animal. Among the earliest measurements of individual activity rhythms using animal-borne devices were those using radio telemetry [@ablesActivityStudiesRed1969; @hutNaturalEntrainmentDawn1999]. When using this technique, the animal is equipped with a radio telemetry collar that continuously transmits a pulse in a certain radiofrequency that can be picked up by a radio receiver tuned to the same frequency. This way it is possible to locate the animal in the field during defined time intervals. Daily activity patterns are inferred by the size of spatial displacements between these time points throughout day and night. Due to the availability of small and lightweight transmitters, this technique can be used on mammals of nearly any size [@naef-daenzerMiniaturizationEvaluationAttachment2005]. Telemetry studies are often done manually, thus being very labor-intense and time-consuming. There are automated telemetry systems, which are a feasible alternative to measure activity patterns, as long as the technical and financial requirements to set up the system can be met and errors due to small body size and large home ranges are taken into account [@kaysTrackingAnimalLocation2011]. Another method that can be used to assess activity patterns based on animal movement are satellite trackers, which previously could only be used in large-sized animals, but are currently being miniaturized [@wikelskiConservationPhysiology2006]. An important advantage of this technique is that data can be obtained remotely, with no need to locate the animal after the tag is deployed. 

Individual-level rhythms can also be measured with newer biologging devices, which are attached to the animal’s body and can record onboard physiological and behavioral parameters including activity, Tb, heart rate and skin humidity [@ropert-coudertTrendsPerspectivesAnimalattached2005; @rutzNewFrontiersBiologging2009]. Given the advancements in the biologging technologies, devices are now smaller and capable of recording multiple parameters in a frequency of hundreds of points per second, providing insight into the details of the animal’s life [@ropert-coudertTrendsPerspectivesAnimalattached2005]. Due to the onboard memory, the main drawback of biologgers is the need to recapture the animals to obtain the data.

Examples of biologging devices used to monitor animal behavior in chronobiological studies include lightloggers and accelerometers. Lightloggers are devices that were originally designed to be used in geolocation in bird migration studies but are particularly interesting for chronobiology. Lightloggers are being used to conduct research on a number of small rodents, recording their temporal patterns of exposure to light. Studies that are benefitted by the use of lightloggers include research on diurnal animals that retreat to nests, subterranean or semi-fossorial animals and hibernating animals in which exposure to light means the animals are active above ground. Accelerometers, in turn, are tri-axial devices that continuously record fine-scale movement. The data generated by accelerometers can be used to quantify gross activity timing, identify behaviors based on movement patterns, quantify time-activity budgets and indirectly derive energy expenditure [@brownObservingUnwatchableAcceleration2013; @ropert-coudertTrendsPerspectivesAnimalattached2005; @rutzNewFrontiersBiologging2009].

Lightloggers were used to investigate the daily and seasonal patterns of activity in wild red squirrels (_Tamiasciurus hudsonicus_) and arctic ground squirrels (_Urocitellus parryii_) [@williamsLightLoggersReveal2014]. Using these devices, they could calculate the total time outside of the nest, the number of activity bouts per day, time of the first emergence in the morning and return to nest at night. They showed that the level of activity was flexible and correlated with changes in the thermoregulatory conditions of the environment. On a different rodent species, the tuco-tuco (genus Ctenomys), a combination of lightloggers and accelerometry was used to investigate the activity patterns of a subterranean rodent in outdoor enclosures [@jannettiDayNightSubterranean2019]. In this study, accelerometers were used to record gross motor activity while lightloggers recorded time on surface. A combination of both methods, therefore, could discriminate levels of aboveground activity and below-ground activity when the animal is inside its burrow system. The study showed that time of day and temperature were the main environmental conditions modulating time spent on the surface [@jannettiDayNightSubterranean2019] and that there was a shift from diurnal to nocturnal levels of activity when the same animals were transferred from outdoor enclosure to controlled laboratory conditions [@jannettiDayNightSubterranean2019; @tachinardiNocturnalDiurnalSwitches2015]. Although this study was done in outdoor enclosures, this approach can also be used in free-ranging animals. Shifts in the timing of activity are also known to happen in other species of rodents besides _Ctenomys sp._ [@hutSearchTemporalNiche2012; @kronfeld-schorChronobiologyInterspecificInteractions2017] and are among the most dramatic discrepancies between rhythms in the field and lab. Biologgers are a helpful addition to approach this phenomenon at the individual level and boost this investigation. The examples provided here highlight possible scenarios where the use of biologging devices can be used to reveal the intimacy and complexity of rhythms in the wild, investigating chronobiological questions and the flexibility of circadian and seasonal rhythms. 

Other alternative technologies can be used to assess rhythms in the wild, such as RFID (Radio Frequency Identification) and newly developed ones such as the BATS system. RFID are small tags that can be used to identify individuals in a population Passive RFID tags do not require their battery to operate and are powered by the energy from the reader's radio waves. They are largely used to identify farm and laboratory animals, being very small and attached either externally or subcutaneously. RFID tags can be used to record activity rhythms by placing readers in locations that the animals visit regularly, such as nests or feeders. This setup allows the recording of the rhythmicity of visits to a specific location where the reader is placed [@vinneMaximisingSurvivalShifting2019]. Although this technique is usually deployed in outdoor enclosures it could be used in free-living animals that have fixed nests or feeding locations. The BATS system is an interesting technology that is fully automated [@dudaBATSAdaptiveUltra2018; @rippergerThinkingSmallNextgeneration2019]. It is composed of small lightweight proximity sensors and a set of receiver stations that are distributed in the study site. The proximity sensors can record interactions between two animals in a sampling rate of seconds and then transmit these data to the base stations. This system can also be used to derive movement trajectory even in structurally complex habitats [@rippergerThinkingSmallNextgeneration2019]. Ripperger and colleagues have used this system to study the behavioral ecology of bats, such as the mother-offspring interactions in noctule bats (_Nyctalus noctule_) [@rippergerProximitySensorsCommon2019] and the social structure of the common vampire bats (_Desmodus rotundus_) [@rippergerVampireBatsThat2019]. Although the BATS system was developed to investigate a different set of questions it seems to be a great new technology to assist in the study of reproduction, social synchronization and the social influences on biological rhythms.

### Physiological rhythms

Biologgers can also be used to assess daily rhythms of physiological variables, enabling the investigation of physiological adjustments to the changes in environmental conditions faced by free-living animals. Tb is the physiological variable most studied in wild chronobiology. It is usually measured and recorded by temperature loggers implanted into the abdomen. This method was used to monitor Tb in free-living arctic ground squirrels (_Urocitellus parryii_) throughout the year, showing that in these animals Tb is arrhythmic during hibernation but displays an entrained 24-hour rhythm in the active season even during the weeks of constant sun [@williamsDataLoggingBody2011]. Monitoring of Tb was also used to record dramatic shifts from diurnally to nocturnality when golden spiny mice (_Acomys russatus_) are transferred from large outdoor enclosures to the laboratory [@levyRelationshipGoldenSpiny2007]. This study is a clear example of how the assessment of physiological rhythms can be important in the investigation of the plasticity of biological rhythms, since the same physiological variable can be measured in both conditions, as opposed to measuring different types of behavioral rhythms under field and laboratory conditions (e.g. foraging in the field and wheel running in the laboratory).

In the laboratory, energy expenditure rhythms can be assessed by measuring hourly rates of oxygen consumption using respirometry chambers, for instance, which is not possible in free-living animals. Since heart rate can be a proxy to energy expenditure, it is a valuable physiological variable in chronobiological studies involving energetics. Heart rate sensors can be attached to the skin, implanted subcutaneously [@toienHibernationBlackBears2011] or even placed non-surgically in the reticulum of ruminants [@signerVersatileTelemetrySystem2010]. These devices can either be loggers [@toienHibernationBlackBears2011] or transmitters [@signerVersatileTelemetrySystem2010].

Brain electrical activity is also of interest to chronobiological studies since it can be used to investigate sleep patterns. Recently, miniature loggers have been developed to measure electrophysiological brain activity [@massotONEIROSNewMiniature2019; @vyssotskiMiniatureNeurologgersFlying2006]. Studies using these loggers have, for instance, provided insights into the ecology of sleep in sloths [@rattenborgSleepingOutsideBox2008] and even indicated that birds can sleep during flight [@rattenborgEvidenceThatBirds2016]. 

## Conclusion

In this mini-review, we highlighted some, but not all, methods that can be applied in chronobiological studies in the wild.  There is a range of new devices and techniques currently being developed that could be applied to free-living animals to assess biological rhythms. The combination of different devices can also be used to discriminate and investigate how some behaviors or physiology interact, even at the cellular and molecular levels [@jansenBearCircadianClock2016]. The fast methodological advancement and the increasing interest of chronobiologists in field studies are key aspects to narrow the gap between what we know about the circadian clocks in the lab and what we know about their functional significance in nature.

## Acknowledgements

We would like to thank Gisele Oda for the revision and suggestions that improved the manuscript; Danilo Flôres, Milene Jannetti and Giovane Improta for discussion of everything chronobiology; and the organizing committee of the XV Latin American Symposium on Chronobiology. JTS was funded in part by the Coordenação de Aperfeiçoamento de Pessoal de Nível Superior - Brasil (CAPES) - Finance Code 001, CAPES scholarship (88882.377383/2019-01) and additional grant from Fundação de Amparo à Pesquisa do Estado de São Paulo (FAPESP) (2017/19680-2). PT was funded by FAPESP fellowship 2017/22973-1.