# Methods

## Study site

Field work was conducted at one site located approximately 5km away from the village of Anillaco, in the province of La Rioja, northwest of Argentina. The study site (-66.95°, -028.80, 1325m) is a relatively undisturbed natural area surrounded by the Sierra de Velasco moutain range, located within the Monte Desert biome. The Monte Desert is characterized as an open shrubland dominated by Zygophyllaceae (_Larrea cuneifolia_ Cav., _Tricomaria usillo_), Fabaceae (_Prosopis torquata_, _Senna aphylla_) and Cactaceae (_Trichocereus_ spp, _Tephrocactus_ spp) [@abrahamOverviewGeographyMonte2009; @aranda-rickertExtrafloralNectarFuels2014; @fracchiaDispersalArbuscularMycorrhizal2011]. At the study site a non-extensive survey of the plant community divided in three transects showed a dominance of the families Zygophyllaceae (_Larrea cuneifolia_, _Tricomaria usillo_), Poaceae (_Microchloa indica_, _Aristida mendocina_) and Fabaceae (_Zuccagnia punctata_) (see Appendix). The climate is arid with marked daily cycle and seasonality in temperature and rainfall (see Appendix). The mean annual temperature is 16.6°C [@fracchiaDispersalArbuscularMycorrhizal2011], with clear differences in the daily range and between summer and winter months [@abrahamOverviewGeographyMonte2009, see Appendix].
The mean annual rainfall ranges from 145 to 380mm concentrated almost exclusively in the summer months [@fracchiaDispersalArbuscularMycorrhizal2011, see Appendix].

<!-- Adicionar Mapa e foto -->

## Study species

- espécie
- possible predators?
- the Ctenomys is a subterranean genus 
- distribution
- 

Todos os animais utilizados são indivíduos adultos (>120g) de C aff. knightii capturados em Anillaco, La Rioja, Argentina (26° 48’ S; 66° 56’ W; 1445 m). Os animais foram capturados em área próxima ao Centro Regional de Pesquisa Cientifica e Transferência Tecnológica de La Rioja (CRILAR). O local de coleta (S28° 47.719' W66° 53.607') possui vegetação nativa, pouca influência antrópica e nenhuma fonte de luz artificial. A região de Anillaco é localizada no Deserto do Monte, de clima semiárido, solo arenoso e com vegetação composta de arbustos, plantas rasteiras e poucas árvores (Fracchia et al, 2011).

## Data collection

- acelerometros
- luximetros
- radiotelemetria
- armadilhas
- permissoes


## Vectorial Dynamic Body Acceleration

Vectorial Dynamic Body Acceleration (VeDBA) was used as a proxy for animal's activity level [@qasemTriAxialDynamicAcceleration2012]. VeDBA was calculated by: (i) Estimating the effect of the gravitational force over the accelerometer, also known as static acceleration. The static acceleration was estimated by applying a moving average over the raw acceleration data. There is not a consensus over the number of points to calculate the moving average, which can be dependent on the study species and device's recording frequency (REF??). Generally, a 1 or 2-second moving average is used to calculated the static acceleration (REF??). However, in the case of the tucos we opted to use a 4-second moving average (40 data points) after following the method proposed by [@shepardDerivationBodyMotion2008] (see Appendix). (ii) Calculating the acceleration correspondent to the animal's movement, also know as Dynamic Body Acceleration (DBA). The DBA was calculated by subtracting the static acceleration from the raw data. (iii) Lastly, we calculate the VeDBA by the vectorial sum of the dynamic acceleration over the device's axis, using:

$$ VeDBA = \sqrt{Xd^2 + Yd^2 + Zd^2} $$
