# -------------------------------------------------------------------------
# Script to asses the best smooth window to use when calculating the
# accelerometer's Dynamic Acceleration and VeDBA. Based on Shepard (2008).
#
# The value found here is the default value for the smoothing window in the DBA 
# function.
#
# Based on the plot generated by this script the default smoothing window was 
# set at 4 sec.
# -------------------------------------------------------------------------

library(data.table)
library(tidyr)
library(zoo)
library(ggplot2)
library(dplyr)

# Read Data
tuco = readRDS("data/rds/tuco_smoothing_window.rds") # This is a subset of 4 animal/4 days
tuco[, day_number := NULL]
tuco[, datetime := NULL]

# Calculate VEDBA using different smoothing windows to subtract the static acceleration (gravity)
windows = seq(from = 1, to = 15, by = 1)
for (i in windows) {
    tuco[, Xs := frollmean(x = X, n = i*10, align = "left"), by = ID]
    tuco[, Ys := frollmean(x = Y, n = i*10, align = "left"), by = ID]
    tuco[, Zs := frollmean(x = Z, n = i*10, align = "left"), by = ID]
    
    tuco[, Xd := X - Xs, by = ID]
    tuco[, Yd := Y - Ys, by = ID]
    tuco[, Zd := Z - Zs, by = ID]
    
    tuco[, paste0("vedba", i) := sqrt(Xd^2 + Yd^2 + Zd^2)]
    
    tuco[, c("Xs","Ys","Zs") := NULL]
    tuco[, c("Xd","Yd","Zd") := NULL]
}
tuco[, c("X","Y","Z") := NULL]

# Calculate mean VEDBA over 10 sec
setkey(tuco, ID)
tuco = tuco[, lapply(X = .SD, FUN = rollapply, width = 100, by = 100, mean), by = ID]

# Transform wide dataset into long dataset
tuco = pivot_longer(tuco, 2:length(tuco), names_to = "smooth", values_to = "vedba")

# Reorganize factor levels
i = 1:15
tuco$smooth = factor(tuco$smooth,
                      levels = c(paste0("vedba", i)))

# PLOTS -------------------------------------------------------------------
tuco.plot = tuco %>% 
    group_by(smooth) %>% 
    summarise(mean = mean(vedba, na.rm = T), sd = sd(vedba, na.rm = T))

library(egg)
(plot = ggplot(tuco.plot) + 
    geom_errorbar(aes(x = smooth, ymin = mean - sd, ymax = mean + sd), width = 0.25, color = "grey") +
    geom_point(aes(x = smooth, y = mean)) +
    theme_article() + 
    theme(panel.grid.major.y = element_line(color = "lightgrey", linetype = "dashed")))

ggsave("plots.png", plot, "png", "smooth_window/plots/", width = 10, height = 8)